### ISSUE TITLE
Basic setup for windows

### ISSUE THREAD

**Issue by Misiur** [Misiur/buster#1]
This issue: https://github.com/axitkhurana/buster/issues/56 so we won't spam in that repository.

@sebie: Yeah, it seems RSS is totally messed up - all links are missing base url, gotta fix that. I basically done everything LeftOrNull done on latest buster version, disabled rewrite wget flag, and added os.remove for duplicate files. Nothing creative on my part

I got it working like this:
1. Create main folder, with src subfolder containing ghost. Run the ghost on **default** host and port, so you don't have to add any flags.
2. Make the main folder your CWD.
3. If you want to deploy run `python buster.py setup` - and set your github repo ssh (not https if you're using ssh-agent), now you should have folders src and static - in static one there's your cloned repo.  
4. Run `python buster.py generate` - if you're running default host:port combo of course
5. Now if you run buster preview on localhost:9000 you should see everything working
6. Deploy if you want

Sorry for writing obvious things, for example I was stuck on the static folder as I thought buster needs some additional working dir for its internal files... If you still have missing assets, show us your output log

**Comment by Misiur** [comment]
Fixed RSS with https://github.com/Misiur/buster/commit/7613143daf1d6bb6e64afae6da384702610534ba, but remember to change `url` in your config.js, so RSS has absolute paths. Oh, also you have to change paths to RSS in your template, because it seems .rss isn't a valid index file...

**Comment by sebie** [comment]
Going to try this now. Will update you.

---

**Update 1**
- What is CWD? Tried using my Google-Fu skills and found a few things, but nothing relevent to the context.
- Default ports, is that `127.0.0.1:2368` ?
- Folder structure please? It is a bit confusing. 

Sorry for my understandings.

**Comment by Misiur** [comment]
Oh, sorry: `Current working directory`.
Port 2368
It doesn't matter where is your ghost, as this will download all files via `127.0.0.1:2368`.
So, if you are in any folder, after running `buster setup` folder `static` will be created

**Comment by sebie** [comment]
Ok, thank you! (And awesome responce time :smile:).

Will update you again, shortly.

**Comment by sebie** [comment]
So:
- Firstly, I updated it to the newst version (yours) -- the one with the RSS fix
- When I preview it, it looks fine (with a few url problems), when the static files looks broken if I just click on them?

**Comment by Misiur** [comment]
I don't quite follow you on that. You mean if you access them via `file:///` url? Then it will be broken. Run buster preview and check out localhost:9000 to see how it will look like. Also, in your config.js did you set the url you want to be final?

**Comment by sebie** [comment]
Sorry. What I was trying to say is when I run `buster preview` (after using `buster generate`) It looks fine, with the exception of the "RSS" link and the "back".

And yes, directly accessing the `file:///` URL is broken.

---

The _Production URL_ is -- "sebie.github.io" with a server of `127.0.0.1` and port `2368`.

The _Development URL_ is -- "http://localhost:2368" with a server of `127.0.0.1` and port `2368`.

---

Hope this helps to clear things up.

**Comment by Misiur** [comment]
Sorry, missed notification mail - in your theme you have to replace links ending with "/rss" to "/rss/index.rss". I don't see "back" in my theme (standard casper one). Where is it located?

**Comment by sebie** [comment]
The "back" button; was located on the top left side of a post. If click it would redirest you to the homepage.

Are the URL's listed above correct?

**Comment by Misiur** [comment]
Ok, you have now two options:
1. Set up development url to sebie.github.io (leave the server set to 127.0.0.1)
2. Set up ghost production config. So, before running `buster generate` you'd have to use `npm start --production`. 
To be honest I'm using the 1st option and works nicely

**Comment by sebie** [comment]
Ok lemme try option 1.

---

Should I use `http` or `https`?

---

Http. 

It might have worked?! 

RSS is broken, but works!

[Link](https://sebie.github.io)

**Comment by Misiur** [comment]
Wonderful. Yeah, your RSS link looks now like http:///rss/. Really weird. Could you show me how does that link look in ghost hbs template?

**Comment by sebie** [comment]
This is my `index.hbs`.

---

_(Prepare for a long paste):_

---

``` html
{{!< default}}
{{! The tag above means - insert everything in this file into the {body} of the default.hbs template }}

{{! The big featured header }}
<header class="main-header {{#if @blog.cover}}" style="background-image: url({{@blog.cover}}){{else}}no-cover{{/if}}">
    <nav class="main-nav overlay clearfix">
        {{#if @blog.logo}}<a class="blog-logo" href="{{@blog.url}}"><img src="{{@blog.logo}}" alt="Blog Logo" /></a>{{/if}}
        <a class="subscribe-button icon-feed" href="{{@blog.url}}/rss/">Subscribe</a>
    </nav>
    <div class="vertical">
        <div class="main-header-content inner">
            <h1 class="page-title">{{@blog.title}}</h1>
            <h2 class="page-description">{{@blog.description}}</h2>
        </div>
    </div>
    <a class="scroll-down icon-arrow-left" href="#content" data-offset="-45"><span class="hidden">Scroll Down</span></a>
</header>

{{! The main content area on the homepage }}
<main id="content" class="content" role="main">

    {{! The tag below includes the post loop - partials/loop.hbs }}
    {{> "loop"}}

</main>
```

I would say it is `line 10`: `<a class="subscribe-button icon-feed" href="{{@blog.url}}/rss/">Subscribe</a>`

**Comment by Misiur** [comment]
Change it to `{{@blog.url}}/rss/index.rss` and it will work

**Comment by sebie** [comment]
Sorry for the late reply, it got buried in my inbox.

Update you soon.

---

I should apply it everywhere, right? `index`, `page`, `post` etc?

Let me try to find a better theme, as I used default so I didn't mess anything up.

**Comment by Misiur** [comment]
Yup, anywhere where rss link is. I think I'll add that to buster script.

**Comment by sebie** [comment]
Ok, tell me if you do. Because then I would have to update buster. 

(Btw; `buster update`?)

**Comment by Misiur** [comment]
Ok, pushed https://github.com/Misiur/buster/commit/150cad19cd294df48506421bb15f4bbb995731f2 (fixes rss link in `<head>` as well). Unfortunately I have no idea how to work with PyPI and forks... I have my repository cloned, and copied my buster.py file (symlinked to be exact, but it's not required) to where I want to use it. Sorry about that.

**Comment by sebie** [comment]
Oh, dw about it. Atleast it works.

**Comment by sebie** [comment]
Also, do you want clean up the Readme so it has the original, but also a description for your modification of it?

**Comment by Misiur** [comment]
It seems you can install stuff using pip via url, so first uninstall old buster using `pip uninstall buster`, and then run `pip install git+https://github.com/Misiur/buster` - and it just works like that! 

Hm, maybe when I have spare few minutes.

**Comment by sebie** [comment]
Nice change. And ok will do the update like you said. Thanks!

**Comment by sebie** [comment]
Everything is working and thank you for the help. I will open an issue if anything messes up or if I have any ideas / suggestions.

**Comment by Misiur** [comment]
You're welcome. If you see some better fork/project - tell me, I would like to use it too :D

**Comment by sebie** [comment]
Deffenitly, but for now this seems to be the best working (out of the box) version!

THank you once again!

**Comment by Loyalsoldier** [comment]
BTW, how to fix the icon-font of the blog? And the static files of the articles do not work.

![screenshot-localhost 9000 2015-10-29 09-52-12](https://cloud.githubusercontent.com/assets/10487845/10808146/c6df03f6-7e22-11e5-8b78-2e1e0258c139.png)

**Comment by Misiur** [comment]
@Loyalsoldier Do you have "/assets/fonts/casper-icons.woff" in your scraped version?

**Comment by Loyalsoldier** [comment]
@Misiur Yes.

BTW,
Just the featured image of the article and the icon-font do not work.

**Comment by Misiur** [comment]
Alright, if you are using chrome go into dev console -> Network tab -> Filter -> fonts - then take a screenshot and show it here (from scraped version, not the one running in node)

**Comment by Loyalsoldier** [comment]
@Misiur 

The Ghost that I'm using is the Chinese-simplified one. And there aren't anything in the `/assets/fonts` folder.

Also, the featured image I set for the article either work well.

Here's the screenshot that I used your buster:

![screenshot-localhost 9000 2015-10-30 15-55-06](https://cloud.githubusercontent.com/assets/10487845/10840912/5766c1b4-7f1f-11e5-949e-c341649dc449.png)

I also use the origin Ghost. Its problem is the same as the Chinese-simplified one.

**Comment by Loyalsoldier** [comment]
But I can manually copy the origin `/assets/fonts` folder to the one in the `static` folder. And it worked. Also the feature image set for the article.

It seems it's a problem about **`absolute path`** and **`relative path`** I guess.

**Comment by Misiur** [comment]
Yeah, now I tried on fresh build and have the same problem. It seems I copied the manually on my blog earlier and forgot. Moved to #3
