### ISSUE TITLE
raise IOError('Your ghost server is dead')

### ISSUE THREAD

**Issue by markstock7** [Misiur/buster#4]
i am working locally, i run the command like this  buster generate --domain=http://localhost:2368/
then i get raise IOError('Your ghost server is dead')

**Comment by Misiur** [comment]
Is your ghost running at localhost:2368?

**Comment by markstock7** [comment]
yes

**Comment by Misiur** [comment]
I can't seem to reproduce that. What's your 1. os version, 2. wget version?
